name: Build and Release APK
on:
  push:
    tags:
      - '*'
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build Release APK
        run: ./gradlew assembleRelease
  Release:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Download APK
        uses: actions/download-artifact@v2
        with:
          name: app-release.apk
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Automatic release of the app-release.apk
          artifacts:
            - app-release.apk
